defaults: &defaults
  working_directory: ~/guardian/portal-plugins-public
  parallelism: 1
  shell: /bin/bash --login
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    PYTHONPATH: /root/virtualenvs/portal-plugins-public/lib/python2.7/site-packages
    NOSE_XUNIT_FILE: /tmp/circleci-test-results/nosetests.xml
    NOSE_WITH_XUNIT: true
    JEST_JUNIT_OUTPUT: /tmp/circleci-test-results/jesttests.xml
  docker:
  #Dockerfile for this is in portal-plugins-private
    - image: 855023211239.dkr.ecr.eu-west-1.amazonaws.com/guardianmultimedia/pluginsbuild:3

version: 2
jobs:
  build_and_test:
    <<: *defaults
    steps:
    - checkout
    - run: yum -y install which; pip install virtualenv nose pep8
    - run: mkdir -p ~/virtualenvs/portal-plugins-public
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: yarn install
    - run: virtualenv ~/virtualenvs/portal-plugins-public
    - run: source ~/virtualenvs/portal-plugins-public/bin/activate && pip install -r test-requirements.txt
    - run: mkdir -p ~/fredex42/gnmvidispine
    - run: git clone https://github.com/fredex42/gnmvidispine  ~/fredex42/gnmvidispine
    - run: cd  ~/fredex42/gnmvidispine; source ~/virtualenvs/portal-plugins-public/bin/activate && python setup.py install
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

    ### set up symlinks and per-plugin build setup
    - run: touch portal/__init__.py; touch portal/plugins/__init__.py
    - run: mkdir -p /opt/cantemo/portal/portal/plugins
    - run: for dir in `find portal/plugins -maxdepth 1 -mindepth 1 -type d | grep -v -E '^\.'`; do echo Symlinking ${dir} to build locations; ln -s ${PWD}/$dir /opt/cantemo/portal/portal/plugins;done
    - run: for dir in `find portal/plugins -maxdepth 1 -mindepth 1 -type d | grep -v -E '^\.'`; do echo Trying to run "${PWD}/$dir/testsetup.sh"; if [ -x "${PWD}/$dir/testsetup.sh" ]; then ${PWD}/$dir/testsetup.sh; fi; done
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/virtualenvs
        - node_modules
        - portal-plugins-public/gnmdownloadablelink/node_modules
        - portal-plugins-private/gnmplutostats/frontend/node_modules

    ### all plugins
    - run: npm run test
    - run: npm run lint
    - run: npm run testcss

    ### gnmpagerduty
    - run: nosetests -v portal/plugins/gnmpagerduty/tests --xunit-file=${CIRCLE_TEST_REPORTS}/gnmpagerduty.xml

    ### gnmlibrarytool
    - run: DJANGO_SETTINGS_MODULE=portal.plugins.gnmlibrarytool.tests.django_test_settings nosetests -v portal/plugins/gnmlibrarytool/tests --xunit-file=${CIRCLE_TEST_REPORTS}/gnmlibrarytool.xml

    ### gnmatomresponder
    - run: DJANGO_SETTINGS_MODULE=portal.plugins.gnmatomresponder.tests.django_test_settings nosetests -v portal/plugins/gnmatomresponder/tests --xunit-file=${CIRCLE_TEST_REPORTS}/gnmatomresponder.xml

    ### gnmoptin
    - run: DJANGO_SETTINGS_MODULE=portal.plugins.gnmoptin.tests.django_test_settings nosetests -v portal/plugins/gnmoptin/tests --xunit-file=${CIRCLE_TEST_REPORTS}/gnmoptin.xml

    ### gnmplutostats
    - run: DJANGO_SETTINGS_MODULE=portal.plugins.gnmplutostats.tests.django_test_settings nosetests -v portal/plugins/gnmplutostats/tests --xunit-file=${CIRCLE_TEST_REPORTS}/gnmplutostats.xml
    - run: cd portal/plugins/gnmplutostats/frontend; nvm use 8.1 && npm run test

    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

    ### deployment
    - run: for dir in `find . -maxdepth 1 -mindepth 1 -type d | awk -F '/' '{ print $2 }' | grep -v -E '^\.'`; do echo Trying to run "${PWD}/$dir/pre_deploy.sh"; if [ -x "${PWD}/$dir/pre_deploy.sh" ]; then ${PWD}/$dir/pre_deploy.sh; fi; done
    - run: rm -f portal/__init__.py; rm -f portal/plugins/__init__.py
    - run: mkdir -p /opt/cantemo/portal/portal/plugins
    - run: rm -rf portal/plugins/gnmdownloadablelink/node_modules
    - run: cd portal/plugins/gnmplutostats/frontend; nvm use 8.1 && npm run build
    - run: rm -rf portal/plugins/gnmplutostats/frontend
    - run: bash ./buildrpms.sh

  common_packages:
    <<: *defaults
    steps:
    ### common packages
    - checkout
    - run: rpmbuild -bb portal-codemirror.spec
    - run: ./upload_with_hash.sh ${HOME}/rpmbuild/RPMS/noarch/portal-codemirror-5.26.0-2.noarch.rpm s3://gnm-multimedia-deployables/gnm_portal_plugins/static/portal-codemirror-5.26.0-2.noarch.rpm
    - run: mkdir -p ${HOME}/rpmbuild/BUILD/static
    - run: cp -a static/chartjs ${HOME}/rpmbuild/BUILD/static
    - run: rpmbuild -bb portal-chartjs.spec
    - run: ./upload_with_hash.sh ${HOME}/rpmbuild/RPMS/noarch/portal-chartjs-1.0-1.noarch.rpm s3://gnm-multimedia-deployables/gnm_portal_plugins/static/portal-chartjs-1.0-1.noarch.rpm
    - run: cp -a static/jquery.cookie.js ${HOME}/rpmbuild/BUILD/static
    - run: rpmbuild -bb portal-jquery-cookie.spec
    - run: ./upload_with_hash.sh ${HOME}/rpmbuild/RPMS/noarch/portal-jquery-cookie-1.4.1-1.noarch.rpm s3://gnm-multimedia-deployables/gnm_portal_plugins/static/portal-jquery-cookie-1.4.1-1.noarch.rpm
    - run: cp -a static/knockout-3.3.0.js ${HOME}/rpmbuild/BUILD/static
    - run: rpmbuild -bb portal-knockout.spec
    - run: ./upload_with_hash.sh ${HOME}/rpmbuild/RPMS/noarch/portal-knockout-3.3.0-1.noarch.rpm s3://gnm-multimedia-deployables/gnm_portal_plugins/static/portal-knockout-3.3.0-1.noarch.rpm
    - run: rpmbuild -bb portal-vkbeautify.spec
    - run: ./upload_with_hash.sh ${HOME}/rpmbuild/RPMS/noarch/portal-vkbeautify-0.99.0-1.noarch.rpm s3://gnm-multimedia-deployables/gnm_portal_plugins/static/portal-vkbeautify-0.99.0-1.noarch.rpm
    - run: rpmbuild -bb portal-fontawesome.spec
    - run: ./upload_with_hash.sh ${HOME}/rpmbuild/RPMS/noarch/portal-fontawesome-4.7.0-1.noarch.rpm s3://gnm-multimedia-deployables/gnm_portal_plugins/static/portal-fontawesome-4.7.0-1.noarch.rpm

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - common_packages